/**
 * Schema migration / bootstrap.
 *
 * Preferred path: apply Drizzle migrations from `./migrations` (generated by
 * `drizzle-kit`). When that folder is absent or empty (e.g. a fresh checkout
 * before any migration has been generated), fall back to an idempotent
 * `CREATE TABLE IF NOT EXISTS` bootstrap derived from the schema so the app is
 * always usable offline.
 */

import { existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { migrate as drizzleMigrate } from 'drizzle-orm/better-sqlite3/migrator';
import { getConnection, type Db } from './connection';

const MIGRATIONS_DIR = join(__dirname, 'migrations');

/** SQL that creates every table if it does not already exist. */
const BOOTSTRAP_SQL = `
CREATE TABLE IF NOT EXISTS parts (
  id TEXT PRIMARY KEY,
  category TEXT NOT NULL,
  manufacturer TEXT NOT NULL,
  model TEXT NOT NULL,
  attributes_json TEXT NOT NULL DEFAULT '{}',
  default_unit TEXT NOT NULL DEFAULT 'pcs',
  standards_version TEXT
);

CREATE TABLE IF NOT EXISTS pricelists (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  currency TEXT NOT NULL DEFAULT 'IDR',
  source_file TEXT,
  imported_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pricelist_items (
  id TEXT PRIMARY KEY,
  pricelist_id TEXT NOT NULL REFERENCES pricelists(id) ON DELETE CASCADE,
  part_id TEXT REFERENCES parts(id) ON DELETE SET NULL,
  match_key TEXT NOT NULL,
  unit_price REAL NOT NULL,
  currency TEXT NOT NULL DEFAULT 'IDR'
);

CREATE TABLE IF NOT EXISTS projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  client TEXT,
  location TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  app_version TEXT,
  earthing_system TEXT
);

CREATE TABLE IF NOT EXISTS panels (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  system TEXT NOT NULL,
  voltage_v REAL NOT NULL,
  frequency_hz REAL NOT NULL DEFAULT 50,
  ambient_temp_c REAL NOT NULL DEFAULT 30,
  install_method TEXT NOT NULL DEFAULT 'conduit',
  grouping_count INTEGER NOT NULL DEFAULT 1,
  active_pricelist_id TEXT REFERENCES pricelists(id) ON DELETE SET NULL,
  diversity_factor REAL NOT NULL DEFAULT 0.8,
  source_type TEXT NOT NULL DEFAULT 'utility',
  fed_by_circuit_id TEXT
);

CREATE TABLE IF NOT EXISTS circuits (
  id TEXT PRIMARY KEY,
  panel_id TEXT NOT NULL REFERENCES panels(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'branch',
  order_index INTEGER NOT NULL DEFAULT 0,
  name TEXT NOT NULL,
  load_w REAL NOT NULL DEFAULT 0,
  cos_phi REAL NOT NULL DEFAULT 0.85,
  length_m REAL NOT NULL DEFAULT 0,
  demand_factor REAL NOT NULL DEFAULT 1,
  load_kind TEXT NOT NULL DEFAULT 'general',
  phase TEXT,
  is_lighting INTEGER NOT NULL DEFAULT 0,
  starter_type TEXT,
  motor_kw REAL,
  motor_poles INTEGER,
  starting_duty TEXT,
  control_mode TEXT,
  sensing TEXT,
  cable_override_mm2 REAL,
  schedule_start_hour INTEGER,
  schedule_end_hour INTEGER,
  feeds_panel_id TEXT,
  chosen_cable_part_id TEXT REFERENCES parts(id) ON DELETE SET NULL,
  chosen_breaker_part_id TEXT REFERENCES parts(id) ON DELETE SET NULL,
  computed_json TEXT
);

CREATE TABLE IF NOT EXISTS control_assemblies (
  id TEXT PRIMARY KEY,
  circuit_id TEXT NOT NULL REFERENCES circuits(id) ON DELETE CASCADE,
  starter_type TEXT NOT NULL,
  motor_kw REAL,
  motor_flc_a REAL,
  motor_poles INTEGER,
  meta_json TEXT
);

CREATE TABLE IF NOT EXISTS assembly_devices (
  id TEXT PRIMARY KEY,
  assembly_id TEXT NOT NULL REFERENCES control_assemblies(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  category TEXT NOT NULL,
  target_rating_a REAL,
  chosen_part_id TEXT REFERENCES parts(id) ON DELETE SET NULL,
  rating TEXT,
  heat_loss_w REAL,
  width_mm REAL,
  qty INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS interlocks (
  id TEXT PRIMARY KEY,
  assembly_id TEXT NOT NULL REFERENCES control_assemblies(id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  device_a_id TEXT NOT NULL,
  device_b_id TEXT NOT NULL,
  relation TEXT NOT NULL,
  note TEXT
);

CREATE TABLE IF NOT EXISTS control_schematics (
  id TEXT PRIMARY KEY,
  circuit_id TEXT NOT NULL REFERENCES circuits(id) ON DELETE CASCADE,
  name TEXT,
  payload_json TEXT
);

CREATE TABLE IF NOT EXISTS schematic_rungs (
  id TEXT PRIMARY KEY,
  schematic_id TEXT NOT NULL REFERENCES control_schematics(id) ON DELETE CASCADE,
  order_index INTEGER NOT NULL DEFAULT 0,
  payload_json TEXT
);

CREATE TABLE IF NOT EXISTS schematic_symbols (
  id TEXT PRIMARY KEY,
  schematic_id TEXT NOT NULL REFERENCES control_schematics(id) ON DELETE CASCADE,
  rung_id TEXT REFERENCES schematic_rungs(id) ON DELETE CASCADE,
  payload_json TEXT
);

CREATE TABLE IF NOT EXISTS schematic_connections (
  id TEXT PRIMARY KEY,
  schematic_id TEXT NOT NULL REFERENCES control_schematics(id) ON DELETE CASCADE,
  from_symbol_id TEXT,
  to_symbol_id TEXT,
  payload_json TEXT
);

CREATE TABLE IF NOT EXISTS system_diagrams (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name TEXT,
  payload_json TEXT
);

CREATE TABLE IF NOT EXISTS system_nodes (
  id TEXT PRIMARY KEY,
  diagram_id TEXT NOT NULL REFERENCES system_diagrams(id) ON DELETE CASCADE,
  panel_id TEXT,
  payload_json TEXT
);

CREATE TABLE IF NOT EXISTS system_edges (
  id TEXT PRIMARY KEY,
  diagram_id TEXT NOT NULL REFERENCES system_diagrams(id) ON DELETE CASCADE,
  from_node_id TEXT,
  to_node_id TEXT,
  payload_json TEXT
);
`;

/** True when the migrations directory exists and holds at least one `.sql` file. */
function hasMigrations(): boolean {
  if (!existsSync(MIGRATIONS_DIR)) return false;
  try {
    return readdirSync(MIGRATIONS_DIR).some((f) => f.endsWith('.sql'));
  } catch {
    return false;
  }
}

/**
 * Bring the database schema up to date. Returns the strategy used so callers can
 * log it. Safe to run on every startup.
 */
export function migrate(db: Db = getConnection().db): 'drizzle' | 'bootstrap' {
  if (hasMigrations()) {
    drizzleMigrate(db, { migrationsFolder: MIGRATIONS_DIR });
    return 'drizzle';
  }
  // Fallback: idempotent table creation straight from the schema.
  getConnection().sqlite.exec(BOOTSTRAP_SQL);
  return 'bootstrap';
}
