/**
 * Drizzle SQLite schema for PanelMaker's local store.
 *
 * Conventions:
 *   - Ids are text UUIDs (generated by the repositories, not the DB).
 *   - Timestamps are ISO-8601 strings (text) for portability across SQLite.
 *   - Structured/engine-derived blobs are stored as JSON text columns suffixed
 *     `_json`; the repositories own (de)serialisation.
 *   - Column names are snake_case; the camelCase domain model is mapped in the
 *     repositories (see `mappers.ts`).
 */

import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

/* -------------------------------------------------------------------------- */
/* Catalog                                                                    */
/* -------------------------------------------------------------------------- */

export const parts = sqliteTable('parts', {
  id: text('id').primaryKey(),
  category: text('category').notNull(),
  manufacturer: text('manufacturer').notNull(),
  model: text('model').notNull(),
  /** Category-specific attributes as JSON text. */
  attributesJson: text('attributes_json').notNull().default('{}'),
  defaultUnit: text('default_unit').notNull().default('pcs'),
  standardsVersion: text('standards_version'),
});

export const pricelists = sqliteTable('pricelists', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  currency: text('currency').notNull().default('IDR'),
  sourceFile: text('source_file'),
  importedAt: text('imported_at').notNull(),
});

export const pricelistItems = sqliteTable('pricelist_items', {
  id: text('id').primaryKey(),
  pricelistId: text('pricelist_id')
    .notNull()
    .references(() => pricelists.id, { onDelete: 'cascade' }),
  partId: text('part_id').references(() => parts.id, { onDelete: 'set null' }),
  matchKey: text('match_key').notNull(),
  unitPrice: real('unit_price').notNull(),
  currency: text('currency').notNull().default('IDR'),
});

/* -------------------------------------------------------------------------- */
/* Project model                                                              */
/* -------------------------------------------------------------------------- */

export const projects = sqliteTable('projects', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  client: text('client'),
  location: text('location'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  appVersion: text('app_version'),
  earthingSystem: text('earthing_system'),
  /** Energy-sources config (generator/solar/battery) as JSON. */
  sourcesJson: text('sources_json'),
  /** Project branding / title-block metadata (ProjectMeta) as JSON. */
  metaJson: text('meta_json'),
});

export const panels = sqliteTable('panels', {
  id: text('id').primaryKey(),
  projectId: text('project_id')
    .notNull()
    .references(() => projects.id, { onDelete: 'cascade' }),
  name: text('name').notNull(),
  /** SystemType: '1ph' | '3ph'. */
  system: text('system').notNull(),
  voltageV: real('voltage_v').notNull(),
  frequencyHz: real('frequency_hz').notNull().default(50),
  ambientTempC: real('ambient_temp_c').notNull().default(30),
  /** InstallMethod. */
  installMethod: text('install_method').notNull().default('conduit'),
  groupingCount: integer('grouping_count').notNull().default(1),
  activePricelistId: text('active_pricelist_id').references(() => pricelists.id, {
    onDelete: 'set null',
  }),
  diversityFactor: real('diversity_factor').notNull().default(0.8),
  /** 'utility' | 'feeder'. */
  sourceType: text('source_type').notNull().default('utility'),
  /** When fed by a parent panel, the upstream feeder circuit id. */
  fedByCircuitId: text('fed_by_circuit_id'),
});

export const circuits = sqliteTable('circuits', {
  id: text('id').primaryKey(),
  panelId: text('panel_id')
    .notNull()
    .references(() => panels.id, { onDelete: 'cascade' }),
  /** 'incomer' | 'branch'. */
  role: text('role').notNull().default('branch'),
  /** Stable ordering within a panel. */
  orderIndex: integer('order_index').notNull().default(0),
  name: text('name').notNull(),
  loadW: real('load_w').notNull().default(0),
  cosPhi: real('cos_phi').notNull().default(0.85),
  lengthM: real('length_m').notNull().default(0),
  demandFactor: real('demand_factor').notNull().default(1),
  /** LoadKind. */
  loadKind: text('load_kind').notNull().default('general'),
  /** SystemType for this circuit's phase context (mirrors panel system). */
  phase: text('phase'),
  isLighting: integer('is_lighting', { mode: 'boolean' }).notNull().default(false),

  // Motor / control
  starterType: text('starter_type'),
  motorKw: real('motor_kw'),
  motorPoles: integer('motor_poles'),
  startingDuty: text('starting_duty'),

  // Pump / level
  controlMode: text('control_mode'),
  sensing: text('sensing'),

  cableOverrideMm2: real('cable_override_mm2'),
  // Daily operating window (absent = continuous) for the load profile.
  scheduleStartHour: integer('schedule_start_hour'),
  scheduleEndHour: integer('schedule_end_hour'),
  /** If this branch feeds a sub-panel, its id. */
  feedsPanelId: text('feeds_panel_id'),

  // Chosen catalog selections (nullable, user/engine driven)
  chosenCablePartId: text('chosen_cable_part_id').references(() => parts.id, {
    onDelete: 'set null',
  }),
  chosenBreakerPartId: text('chosen_breaker_part_id').references(() => parts.id, {
    onDelete: 'set null',
  }),

  /** Cached engine CircuitResult as JSON (optional, recomputable). */
  computedJson: text('computed_json'),
});

/* -------------------------------------------------------------------------- */
/* Control gear bill                                                          */
/* -------------------------------------------------------------------------- */

export const controlAssemblies = sqliteTable('control_assemblies', {
  id: text('id').primaryKey(),
  circuitId: text('circuit_id')
    .notNull()
    .references(() => circuits.id, { onDelete: 'cascade' }),
  starterType: text('starter_type').notNull(),
  motorKw: real('motor_kw'),
  motorFlcA: real('motor_flc_a'),
  motorPoles: integer('motor_poles'),
  /** Pump configuration + warnings as JSON. */
  metaJson: text('meta_json'),
});

export const assemblyDevices = sqliteTable('assembly_devices', {
  id: text('id').primaryKey(),
  assemblyId: text('assembly_id')
    .notNull()
    .references(() => controlAssemblies.id, { onDelete: 'cascade' }),
  role: text('role').notNull(),
  category: text('category').notNull(),
  targetRatingA: real('target_rating_a'),
  chosenPartId: text('chosen_part_id').references(() => parts.id, {
    onDelete: 'set null',
  }),
  rating: text('rating'),
  heatLossW: real('heat_loss_w'),
  widthMm: real('width_mm'),
  qty: integer('qty').notNull().default(1),
});

export const interlocks = sqliteTable('interlocks', {
  id: text('id').primaryKey(),
  assemblyId: text('assembly_id')
    .notNull()
    .references(() => controlAssemblies.id, { onDelete: 'cascade' }),
  kind: text('kind').notNull(),
  deviceAId: text('device_a_id').notNull(),
  deviceBId: text('device_b_id').notNull(),
  relation: text('relation').notNull(),
  note: text('note'),
});

/* -------------------------------------------------------------------------- */
/* Schematics (persistence stubs for the renderer's diagram state)            */
/* -------------------------------------------------------------------------- */

export const controlSchematics = sqliteTable('control_schematics', {
  id: text('id').primaryKey(),
  circuitId: text('circuit_id')
    .notNull()
    .references(() => circuits.id, { onDelete: 'cascade' }),
  name: text('name'),
  payloadJson: text('payload_json'),
});

export const schematicRungs = sqliteTable('schematic_rungs', {
  id: text('id').primaryKey(),
  schematicId: text('schematic_id')
    .notNull()
    .references(() => controlSchematics.id, { onDelete: 'cascade' }),
  orderIndex: integer('order_index').notNull().default(0),
  payloadJson: text('payload_json'),
});

export const schematicSymbols = sqliteTable('schematic_symbols', {
  id: text('id').primaryKey(),
  schematicId: text('schematic_id')
    .notNull()
    .references(() => controlSchematics.id, { onDelete: 'cascade' }),
  rungId: text('rung_id').references(() => schematicRungs.id, {
    onDelete: 'cascade',
  }),
  payloadJson: text('payload_json'),
});

export const schematicConnections = sqliteTable('schematic_connections', {
  id: text('id').primaryKey(),
  schematicId: text('schematic_id')
    .notNull()
    .references(() => controlSchematics.id, { onDelete: 'cascade' }),
  fromSymbolId: text('from_symbol_id'),
  toSymbolId: text('to_symbol_id'),
  payloadJson: text('payload_json'),
});

/* -------------------------------------------------------------------------- */
/* System (single-line) diagram layout (persistence stubs)                    */
/* -------------------------------------------------------------------------- */

export const systemDiagrams = sqliteTable('system_diagrams', {
  id: text('id').primaryKey(),
  projectId: text('project_id')
    .notNull()
    .references(() => projects.id, { onDelete: 'cascade' }),
  name: text('name'),
  payloadJson: text('payload_json'),
});

export const systemNodes = sqliteTable('system_nodes', {
  id: text('id').primaryKey(),
  diagramId: text('diagram_id')
    .notNull()
    .references(() => systemDiagrams.id, { onDelete: 'cascade' }),
  /** The panel (or other entity) this node represents, when applicable. */
  panelId: text('panel_id'),
  payloadJson: text('payload_json'),
});

export const systemEdges = sqliteTable('system_edges', {
  id: text('id').primaryKey(),
  diagramId: text('diagram_id')
    .notNull()
    .references(() => systemDiagrams.id, { onDelete: 'cascade' }),
  fromNodeId: text('from_node_id'),
  toNodeId: text('to_node_id'),
  payloadJson: text('payload_json'),
});

/* -------------------------------------------------------------------------- */
/* The full schema map (passed to drizzle()) and inferred row types           */
/* -------------------------------------------------------------------------- */

export const schema = {
  parts,
  pricelists,
  pricelistItems,
  projects,
  panels,
  circuits,
  controlAssemblies,
  assemblyDevices,
  interlocks,
  controlSchematics,
  schematicRungs,
  schematicSymbols,
  schematicConnections,
  systemDiagrams,
  systemNodes,
  systemEdges,
};

export type PartRow = typeof parts.$inferSelect;
export type NewPartRow = typeof parts.$inferInsert;
export type PricelistRow = typeof pricelists.$inferSelect;
export type NewPricelistRow = typeof pricelists.$inferInsert;
export type PricelistItemRow = typeof pricelistItems.$inferSelect;
export type NewPricelistItemRow = typeof pricelistItems.$inferInsert;
export type ProjectRow = typeof projects.$inferSelect;
export type NewProjectRow = typeof projects.$inferInsert;
export type PanelRow = typeof panels.$inferSelect;
export type NewPanelRow = typeof panels.$inferInsert;
export type CircuitRow = typeof circuits.$inferSelect;
export type NewCircuitRow = typeof circuits.$inferInsert;
export type ControlAssemblyRow = typeof controlAssemblies.$inferSelect;
export type AssemblyDeviceRow = typeof assemblyDevices.$inferSelect;
export type InterlockRow = typeof interlocks.$inferSelect;
